config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'questions#index'

  resources :questions do
    resources :answers, except: :index do
      patch :mark_as_solution, on: :member
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :body, presence: true
  belongs_to :question
  belongs_to :user

  has_many :attachments, as: :attachable

  accepts_nested_attributes_for :attachments, allow_destroy: true

  scope :order_by_solution, -> { order(is_solution: :desc) }

  def mark_as_solution
    self.question.answers.update_all(is_solution: false)
    self.update(is_solution: true)
  end
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  mount_uploader :file, FileUploader

  belongs_to :attachable, polymorphic: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :body, presence: true
  has_many :answers, dependent: :destroy
  has_many :attachments, as: :attachable
  belongs_to :user

  accepts_nested_attributes_for :attachments, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :questions
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question
  before_action :set_answer, only: [:destroy, :update, :mark_as_solution]

  def create
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def destroy
    @answer.destroy if current_user.id == @answer.user_id
  end

  def update
    @question = @answer.question
    if current_user.id == @answer.user_id
      @answer.update(answer_params)
    else
      redirect_to @question, notice: 'Access denied'
    end
  end

  def mark_as_solution
    @question = @answer.question
    @answer.mark_as_solution if @question.user_id == current_user.id
  end

  private

  def answer_params
    params.require(:answer).permit(:body, :question_id, :is_solution, attachments_attributes: [:file, :id, :_destroy])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @answer.attachments.build
  end

  def new
    @question = Question.new
    @question.attachments.build
  end

  def edit
    redirect_to root_path, notice: "Access denied" unless current_user.id == @question.user_id
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user

    if @question.save
      redirect_to @question, notice: 'Question was successfully created'
    else
      render :new
    end
  end

  def update
    if current_user.id == @question.user_id && @question.update(question_params)
      redirect_to @question, notice: 'Question was successfully updated'
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @question.user_id
      @question.destroy
      redirect_to questions_path, notice: 'Question was deleted'
    else
      redirect_to root_path, notice: 'You can delete only questions you own'
    end
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nice_datetime(date)
    date.strftime('%c')
  end

  def alert_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  div.answer id=dom_id(answer) class=('solution' if answer.is_solution?)
    p= nice_datetime(answer.created_at)
    small= answer.user.email
    br
    - if user_signed_in? && current_user.id == answer.user_id
      => link_to 'Edit', '', class: 'edit-answer-link', data: { answer_id: answer.id }
      = link_to 'Delete', question_answer_path(@question, answer), data: { confirm: 'Are you sure?', method: :delete, remote: true }
      - unless answer.is_solution?
        p= link_to 'Mark as solution', mark_as_solution_question_answer_path(@question, answer), data: { remote: true, method: :patch }

    - if answer.is_solution?
      strong= 'Marked as solution'

    p = answer.body
    p Attachments
    ul
      - answer.attachments.each do |a|
        li = link_to a.file.identifier, a.file.url

    = simple_nested_form_for [@question, answer], remote: true, html: { id: "edit-answer-#{answer.id}" }, class: 'edit-answer' do |f|
      = f.input :body, label: 'Edit your answer'

      = f.button :submit



    hr

app/views/answers/_form.html.slim
= simple_nested_form_for [@question, @answer], remote: true do |f|
  .answer-errors
  = f.input :body, label: 'Your answer'

  .form-group
    = render 'shared/attachment_fields', f: f


  = f.button :submit, 'Add answer'

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').append("<%= j render @answer %>");
  $('#answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('#<%= dom_id(@answer) %>').remove();

app/views/answers/mark_as_solution.js.erb
$('.answers').html("<%= j render @question.answers.order_by_solution %>");

app/views/answers/update.js.erb
<% if @answer.errors.any? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('#answer_<%= @answer.id %>').html("<%= j render @answer %>");
  $('.edit-answer-link').click(function (e) {
    e.preventDefault();
    $(this).hide();
    answer_id = $(this).data('answerId');
    $('form#edit-answer-' + answer_id).show();
  });
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stackoverclone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/nav' %>

<div class="container">
  <%= render 'shared/flash_messages', flash: flash %>
</div>

<div class='container'>
  <%= yield %>
</div>

</body>
</html>

app/views/questions/_form.html.slim
= simple_nested_form_for question do |f|
  = f.input :title
  = f.input :body

  .form-group
    = render 'shared/attachment_fields', f: f

  = f.button :submit

app/views/questions/edit.html.slim
h2 Edit question

= render 'form', question: @question

app/views/questions/index.html.slim
h1 Questions

= link_to 'Ask new question', new_question_path, class: 'btn btn-default' if current_user

- @questions.each do |question|
  p.question= link_to question.title, question

app/views/questions/new.html.slim
h2 New question

= render 'form', question: @question

app/views/questions/show.html.slim
h2 = @question.title
- if current_user && @question.user_id == current_user.id
  small => link_to 'Edit question', edit_question_path(@question)
  small = link_to 'Delete question', @question, data: { method: :delete, confirm: 'Are you sure?' }

h4 = "Author: #{@question.user.email}"
p = @question.body
p Attachments
ul
  - @question.attachments.each do |a|
    li = link_to a.file.identifier, a.file.url

.answers = render @question.answers.order_by_solution

- if current_user
  = render 'answers/form'
- else
  | Sign in or sign up to leave answers

app/views/shared/_attachment_fields.html.slim
.nested_fields
  = f.simple_fields_for :attachments do |a|
    = a.input :file
    = a.link_to_remove 'Remove this file'
  = f.link_to_add 'Add attachment', :attachments

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_nav.html.slim
nav.navbar.navbar-default role="navigation"
  .container
    .navbar-header
      = link_to 'StackOverclone', root_path, class: 'navbar-brand'

    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if current_user
          li= link_to 'Settings', edit_user_registration_path
          li= link_to 'Logout', destroy_user_session_path, data: {method: :delete}
        - else
          li= link_to 'Login', new_user_session_path
          li= link_to 'Register', new_user_registration_path